name: azure-blob-storage
 
on:
  push:
    branches:
      - main
 
env:
  AZURE_RESOURCE_GROUP: react-demo
  BLOB_STORAGE_ACCOUNT_NAME: reactdemoui
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        cd react-demo
        npm install
        npm run build
        pwd
        ls

    
 

 
    # Authentication
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: check pwd
      run: |
         pwd
         ls
         cd react-demo/build
 
    # Deploy to storage using CLI
    - name: Deploy to storage using CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: | 
          ls
          cd react-demo
          # show azure account being used
          az account show
          #az storage blob upload-batch --account-name ${{ env.BLOB_STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s .

          # az storage account upload
          az storage blob upload-batch --destination demo-container --source .build/ --account-name reactdemoui   